name: ❓ Questions and Help
description: If you have questions, please check the below links.
title: "Questions or Help"
labels: question
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have you read the Contributing Guidelines? [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

  - type: dropdown
    attributes:
      label: Initiative (Required)
      description: "Please choose the initiative you are contributing to:"
      options:
        - GSSoC (Girl Script Summer of Code) 🌸
        - GSSoC 2024 Extd 🚀
        - Hacktoberfest 2024 🎃
        - Script Winter of Code (SWoC) ❄️
        - Winter of Blockchain (WoB) ⛄
        - Personal 🧑‍💻
        - "Other (please specify): _______________ ✏️"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Info
      description: "Please provide any additional information or questions you may have."
      placeholder: Type here...
    validations:
      required: false
